import "../comp/style/common.scss"
import M_footer from "../comp/UIUX/M_footer";
import M_header from "../comp/UIUX/M_header";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <M_header />
        {children}
        <M_footer />
      </body>
    </html>
  );
}
